import AppKit

/// Community sensitivity markers (nspasteboard.org). Not declared by AppKit; advisory only.
enum Markers {
    static let concealed = "org.nspasteboard.ConcealedType"
    static let transient = "org.nspasteboard.TransientType"
    static let autoGenerated = "org.nspasteboard.AutoGeneratedType"
    static let source = "org.nspasteboard.source"
    static let legacyTransient = "de.petermaurer.TransientPasteboardType"
    static let onePassword = "com.agilebits.onepassword"
    static let remoteClipboard = "com.apple.is-remote-clipboard"

    static let all = [concealed, transient, autoGenerated, source, legacyTransient,
                      onePassword, remoteClipboard]

    static func present(in types: [String]) -> [String] {
        all.filter { types.contains($0) }
    }
}

/// One pasteboard item captured as type identifiers plus hashes/lengths. Never holds
/// payloads longer than needed for restore, and never logs them.
struct ItemSnapshot {
    var types: [String]
    var payloads: [String: Data]
    var unreadableTypes: [String]

    var describedTypes: [String] {
        types.map { type in
            if let data = payloads[type] {
                return "\(type)(len=\(data.count),sha=\(Digest.short(data)))"
            }
            return "\(type)(UNREADABLE)"
        }
    }
}

struct PasteboardSnapshot {
    var changeCount: Int
    var items: [ItemSnapshot]
    var takenAtMs: Double

    var fingerprint: String {
        items.map { $0.describedTypes.joined(separator: ",") }.joined(separator: " | ")
    }
}

enum Clipboard {
    static let board = NSPasteboard.general

    /// Set just before a probe-initiated write so the watcher can report true copy->detect latency.
    static var markedWriteAt: UInt64?

    // MARK: - Metadata-only access (no content read)

    static func changeCount() -> Int { board.changeCount }

    static func typesOnly() -> [String] {
        (board.types ?? []).map { $0.rawValue }
    }

    static func itemTypesOnly() -> [[String]] {
        (board.pasteboardItems ?? []).map { item in item.types.map { $0.rawValue } }
    }

    // MARK: - Content access (logged as length + hash only)

    static func snapshot(readData: Bool = true) -> PasteboardSnapshot {
        let (snapshot, ms) = Clock.measure { () -> PasteboardSnapshot in
            let count = board.changeCount
            var items: [ItemSnapshot] = []
            for item in board.pasteboardItems ?? [] {
                var payloads: [String: Data] = [:]
                var unreadable: [String] = []
                let types = item.types.map { $0.rawValue }
                if readData {
                    for type in item.types {
                        if let data = item.data(forType: type) {
                            payloads[type.rawValue] = data
                        } else {
                            unreadable.append(type.rawValue)
                        }
                    }
                }
                items.append(ItemSnapshot(types: types, payloads: payloads,
                                          unreadableTypes: unreadable))
            }
            return PasteboardSnapshot(changeCount: count, items: items, takenAtMs: 0)
        }
        var result = snapshot
        result.takenAtMs = ms
        return result
    }

    /// Restores a snapshot. Returns the change count produced by our own write, so a later
    /// comparison can tell whether somebody else wrote after us.
    @discardableResult
    static func restore(_ snapshot: PasteboardSnapshot) -> (ownedCount: Int, failures: [String]) {
        var failures: [String] = []
        let owned = board.clearContents()
        var objects: [NSPasteboardItem] = []
        for item in snapshot.items {
            let restored = NSPasteboardItem()
            for type in item.types {
                guard let data = item.payloads[type] else {
                    failures.append("no-data:\(type)")
                    continue
                }
                if !restored.setData(data, forType: NSPasteboard.PasteboardType(type)) {
                    failures.append("setData-failed:\(type)")
                }
            }
            objects.append(restored)
        }
        if !objects.isEmpty, !board.writeObjects(objects) {
            failures.append("writeObjects-failed")
        }
        return (owned, failures)
    }

    /// Writes probe-owned synthetic text, marked transient/auto-generated and host-only.
    @discardableResult
    static func writeSynthetic(_ text: String, markTransient: Bool = true) -> Int {
        let count = board.prepareForNewContents(with: .currentHostOnly)
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        if markTransient {
            item.setString("", forType: NSPasteboard.PasteboardType(Markers.transient))
            item.setString("", forType: NSPasteboard.PasteboardType(Markers.autoGenerated))
            item.setString(ProbeIdentity.bundleID,
                           forType: NSPasteboard.PasteboardType(Markers.source))
        }
        board.writeObjects([item])
        return count
    }

    static func describe(_ snapshot: PasteboardSnapshot, label: String) {
        Log.line("\(label) changeCount=\(snapshot.changeCount) items=\(snapshot.items.count) readMs=\(snapshot.takenAtMs)")
        for (index, item) in snapshot.items.enumerated() {
            let markers = Markers.present(in: item.types)
            Log.line("  item[\(index)] types=\(item.describedTypes.joined(separator: " "))"
                     + (markers.isEmpty ? "" : " MARKERS=\(markers.joined(separator: ","))"))
        }
    }
}

/// changeCount poller — the only supported observation mechanism on macOS.
final class ClipboardWatcher {
    private var timer: Timer?
    private var lastCount: Int = Clipboard.changeCount()
    private var lastChangeAt = Date()
    private(set) var intervalMs: Double = 200
    private(set) var observations = 0
    var readContent = false

    func start(intervalMs: Double, readContent: Bool) {
        stop()
        self.intervalMs = intervalMs
        self.readContent = readContent
        lastCount = Clipboard.changeCount()
        Log.line("watch START interval=\(intervalMs)ms readContent=\(readContent) baseChangeCount=\(lastCount)")
        let timer = Timer(timeInterval: intervalMs / 1000.0, repeats: true) { [weak self] _ in
            self?.tick()
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        if timer != nil { Log.line("watch STOP observations=\(observations)") }
        timer?.invalidate()
        timer = nil
    }

    private func tick() {
        let current = Clipboard.changeCount()
        guard current != lastCount else { return }
        observations += 1
        let detectLatency = (Date().timeIntervalSince(lastChangeAt) * 1000).rounded()
        lastCount = current
        lastChangeAt = Date()
        if let written = Clipboard.markedWriteAt {
            let latency = Double(DispatchTime.now().uptimeNanoseconds - written) / 1_000_000.0
            Log.line("LATENCY copy->detect \((latency * 100).rounded() / 100)ms (poll interval \(intervalMs)ms)")
            Clipboard.markedWriteAt = nil
        }

        let types = Clipboard.itemTypesOnly()
        let flat = types.flatMap { $0 }
        let markers = Markers.present(in: flat)
        Log.line("COPY detected changeCount=\(current) sincePrevChange=\(detectLatency)ms "
                 + "items=\(types.count) types=\(flat.joined(separator: ","))"
                 + (markers.isEmpty ? "" : " MARKERS=\(markers.joined(separator: ","))"))
        if !markers.isEmpty {
            Log.line("  -> a cooperative marker is present; a real client must skip recording this item")
        }
        if readContent {
            if markers.contains(Markers.concealed) || markers.contains(Markers.transient) {
                Log.line("  -> content read SKIPPED (marker says do not record)")
                return
            }
            let snapshot = Clipboard.snapshot()
            Clipboard.describe(snapshot, label: "  contentRead")
        }
    }
}
