import AppKit

/// Community pasteboard markers (nspasteboard.org and legacy producers). AppKit declares none of them; they are
/// advisory conventions set by cooperative apps such as password managers.
enum PasteboardMarkers {
    static let concealed = NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType")
    static let transient = NSPasteboard.PasteboardType("org.nspasteboard.TransientType")
    static let autoGenerated = NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    static let source = NSPasteboard.PasteboardType("org.nspasteboard.source")

    /// Markers that ask clipboard observers not to keep the copy: it becomes the Active Item but is never
    /// stored, and the Pre-check refuses to smart-paste it.
    static let concealing: Set<NSPasteboard.PasteboardType> = [
        concealed,
        transient,
        autoGenerated,
        NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType"),
        NSPasteboard.PasteboardType("com.typeit4me.clipping"),
        NSPasteboard.PasteboardType("Pasteboard generator type"),
        NSPasteboard.PasteboardType("com.agilebits.onepassword"),
    ]

    /// Whether the pasteboard's declared types carry a concealing marker. Reads types only, never content.
    static func conceal(_ pasteboard: NSPasteboard) -> Bool {
        !concealing.isDisjoint(with: pasteboard.types ?? [])
    }
}
