import AppKit
import SmartPasteCore

/// The `Clipboard` adapter over an `NSPasteboard` (the general pasteboard in the app).
///
/// Own writes are host-only and carry the transient/auto-generated markers so other clipboard managers skip the
/// temporary Paste Result. Changes are observed by polling `changeCount` on the `PollingSchedule`.
@MainActor
public final class SystemClipboard: Clipboard {
    /// The bundle identifier written as `org.nspasteboard.source` on our own writes.
    static let sourceIdentifier = "com.jevpaste.JevPaste"

    private let pasteboard: NSPasteboard
    private let pollingSchedule: any PollingSchedule

    public init(
        pasteboard: NSPasteboard = .general,
        pollingSchedule: any PollingSchedule = TimerPollingSchedule(interval: .milliseconds(100))
    ) {
        self.pasteboard = pasteboard
        self.pollingSchedule = pollingSchedule
    }

    public var changeCount: Int { pasteboard.changeCount }

    public func snapshot() -> ClipboardSnapshot {
        let items = (pasteboard.pasteboardItems ?? []).map { item in
            item.types.reduce(into: [String: Data]()) { bytesByType, type in
                bytesByType[type.rawValue] = item.data(forType: type)
            }
        }
        return ClipboardSnapshot(items: items)
    }

    public func write(_ text: String) -> Int {
        pasteboard.prepareForNewContents(with: .currentHostOnly)
        let item = NSPasteboardItem()
        item.setString(text, forType: .string)
        item.setString("", forType: PasteboardMarkers.transient)
        item.setString("", forType: PasteboardMarkers.autoGenerated)
        item.setString(Self.sourceIdentifier, forType: PasteboardMarkers.source)
        pasteboard.writeObjects([item])
        return pasteboard.changeCount
    }

    public func restore(_ snapshot: ClipboardSnapshot) -> Int {
        pasteboard.clearContents()
        let items = snapshot.items.map { bytesByType in
            let item = NSPasteboardItem()
            for (type, bytes) in bytesByType {
                item.setData(bytes, forType: NSPasteboard.PasteboardType(type))
            }
            return item
        }
        if !items.isEmpty {
            pasteboard.writeObjects(items)
        }
        return pasteboard.changeCount
    }

    public func startObservingChanges(_ onChange: @escaping @MainActor (ClipboardChange) -> Void) {
        let pasteboard = pasteboard
        var lastObservedCount = pasteboard.changeCount
        pollingSchedule.start {
            guard pasteboard.changeCount != lastObservedCount else { return }
            lastObservedCount = pasteboard.changeCount
            onChange(ClipboardChange(changeCount: lastObservedCount, item: Self.currentItem(on: pasteboard)))
        }
    }

    /// The text on the clipboard right now as a Clipboard Item, or `nil` when it holds no text. Read once at
    /// launch to seed the Active Item; not part of the `Clipboard` port. Markers are checked before the content.
    public func currentItem() -> ClipboardItem? {
        Self.currentItem(on: pasteboard)
    }

    /// The current text as a Clipboard Item. Markers are checked before the content is read.
    private static func currentItem(on pasteboard: NSPasteboard) -> ClipboardItem? {
        let isConcealed = PasteboardMarkers.conceal(pasteboard)
        guard let text = pasteboard.string(forType: .string) else { return nil }
        return ClipboardItem(text: text, isConcealed: isConcealed)
    }
}
