import AppKit
import MacInterop
import SmartPasteCore
import Testing

@MainActor
struct ClipboardObservationTests {
    private let scratch = ScratchPasteboard()
    private var pasteboard: NSPasteboard { scratch.pasteboard }
    private let schedule = ManualPollingSchedule()

    private func observedClipboard() -> (SystemClipboard, ChangeRecorder) {
        let clipboard = SystemClipboard(pasteboard: pasteboard, pollingSchedule: schedule)
        let recorder = ChangeRecorder()
        clipboard.startObservingChanges { recorder.changes.append($0) }
        return (clipboard, recorder)
    }

    @Test func ownWriteIsReportedOnlyOnALaterTickWithItsChangeCount() {
        let (clipboard, recorder) = observedClipboard()

        let ownCount = clipboard.write("Jane Doe")
        #expect(recorder.changes.isEmpty)

        schedule.tick()
        #expect(recorder.changes.map(\.changeCount) == [ownCount])
    }

    @Test func foreignCopyIsReportedOnceWithItsText() {
        let (_, recorder) = observedClipboard()

        scratch.copyLikeAnotherApp(["public.utf8-plain-text": Data("Jane Doe\njane@example.com".utf8)])
        schedule.tick()
        schedule.tick()

        #expect(recorder.changes.map(\.item) == [ClipboardItem(text: "Jane Doe\njane@example.com")])
    }

    @Test func restoredContentsAreReportedWithTheirText() {
        let (clipboard, recorder) = observedClipboard()
        let original = ClipboardSnapshot(items: [["public.utf8-plain-text": Data("original".utf8)]])

        let restoredCount = clipboard.restore(original)
        schedule.tick()

        #expect(
            recorder.changes == [ClipboardChange(changeCount: restoredCount, item: ClipboardItem(text: "original"))])
    }

    @Test func copyWithoutTextIsReportedWithoutAnItem() {
        let (_, recorder) = observedClipboard()

        scratch.copyLikeAnotherApp(["public.png": Data([0x89, 0x50])])
        schedule.tick()

        #expect(recorder.changes.count == 1)
        #expect(recorder.changes.first?.item == nil)
    }

    @Test(arguments: [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "de.petermaurer.TransientPasteboardType",
        "com.typeit4me.clipping",
        "Pasteboard generator type",
        "com.agilebits.onepassword",
    ])
    func markedCopyIsReportedAsConcealed(marker: String) {
        let (_, recorder) = observedClipboard()

        scratch.copyLikeAnotherApp(["public.utf8-plain-text": Data("hunter2".utf8), marker: Data()])
        schedule.tick()

        #expect(recorder.changes.map(\.item) == [ClipboardItem(text: "hunter2", isConcealed: true)])
    }

    @Test func unmarkedCopyIsNotConcealed() {
        let (_, recorder) = observedClipboard()

        scratch.copyLikeAnotherApp([
            "public.utf8-plain-text": Data("hello".utf8), "org.nspasteboard.source": Data("com.example".utf8),
        ])
        schedule.tick()

        #expect(recorder.changes.first?.item?.isConcealed == false)
    }

    @Test func ownWriteCarriesTheMarkersThatKeepOtherClipboardManagersAway() {
        let (clipboard, recorder) = observedClipboard()

        _ = clipboard.write("Jane Doe")
        schedule.tick()

        let types = Set(pasteboard.pasteboardItems?.first?.types.map(\.rawValue) ?? [])
        #expect(types.isSuperset(of: ["org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]))
        #expect(pasteboard.string(forType: NSPasteboard.PasteboardType("org.nspasteboard.source")) != nil)
        #expect(recorder.changes.first?.item == ClipboardItem(text: "Jane Doe", isConcealed: true))
    }
}

@MainActor
final class ChangeRecorder {
    var changes: [ClipboardChange] = []
}
